apiVersion: v2
appVersion: 1.0.0
description: The Apache Hive ™ data warehouse software facilitates reading, writing, and managing large datasets
  residing in distributed storage using SQL. Structure can be projected onto data already in storage. A command
  line tool and JDBC driver are provided to connect users to Hive.
home: https://hive.apache.org/
icon: https://hive.apache.org/images/hive_logo_medium.jpg
maintainers:
- email: m.prestifilippo@gmail.com
  name: p11o
name: hive-metastore
version: 1.0.0
dependencies:
- name: postgresql
  version: ~11
  repository: https://charts.bitnami.com/bitnami
