
version: 2

models:
  - name: household
    description: "Basic household model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - not_null
